controllers:
  resource: ../src/Controller/
  type: annotation

# index:
# path: /
# controller: App\Controller\MixedTapeController::homepage

kernel:
  resource: ../src/Kernel.php
  type: annotation
